# part of our backport process, see `backport-on-comment.py`
name: backport on comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request && github.event.comment && startsWith(github.event.comment.body, '@pytestbot please backport')

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools tox
    - name: Prepare release
      run: |
        tox -e backport-on-comment -- $GITHUB_EVENT_PATH ${{ secrets.chatops }}
